# Generated by Django 3.0 on 2020-09-07 12:46

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200907_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=128, populate_from=('title', 'id'), unique=True, verbose_name='slug'),
        ),
    ]
