# Generated by Django 3.0 on 2020-09-07 12:47

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=('title', 'id'), unique=True, verbose_name='slug'),
        ),
    ]
