# Generated by Django 3.0 on 2020-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='helo'),
            preserve_default=False,
        ),
    ]
