# Generated by Django 3.0 on 2020-09-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200917_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default_card.jpg', upload_to=''),
        ),
    ]
